baseurl = "/"
languageCode = "en-us"
title = "Liang's Blog"
theme = "hugo-ivy"
<img src="https://wx2.sbimg.cn/2020/09/22/G1Dpw.md.jpg" style="max-width:15%;min-width:40px;float:right;" alt="Logo" />
enableEmoji = true
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# Enable global LaTeX math rendering?
# If false, you can enable it locally on a per page basis.
math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "一个训练‘其神凝 ’的内景"
    footer = "&copy; [Liang Zhang](https://lzhang.space) 2018-2020 | [Weibo](https://weibo.com/edgeofworld) | [B站](https://space.bilibili.com/13756957)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
